# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'V6.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import pyqtgraph as pg
from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime

class TimeAxisItem(pg.AxisItem):
    def tickStrings(self, values, scale, spacing):
        return [datetime.fromtimestamp(int(values[n]/1000)) for n in range(len(values))]

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1096, 809)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 60, 531, 321))
        self.groupBox.setObjectName("groupBox")
        self.graphicsViewI = pg.ImageView(self.groupBox)
        self.graphicsViewI.setGeometry(QtCore.QRect(10, 20, 511, 281))
        self.graphicsViewI.setObjectName("graphicsViewI")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(570, 40, 21, 691))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.comboBox2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox2.setGeometry(QtCore.QRect(700, 10, 69, 31))
        self.comboBox2.setObjectName("comboBox2")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(620, 10, 81, 21))
        self.label2.setObjectName("label2")
        # ----------------------------------------------------
        self.date_axis_1 = TimeAxisItem(orientation='bottom')
        self.date_axis_2 = TimeAxisItem(orientation='bottom')
        self.date_axis_3 = TimeAxisItem(orientation='bottom')
        # ----------------------------------------------------
        self.graphicsView_2 = pg.PlotWidget(self.centralwidget, axisItems = {'bottom': self.date_axis_1})
        self.graphicsView_2.setGeometry(QtCore.QRect(610, 50, 471, 221))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.comboBox1 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox1.setGeometry(QtCore.QRect(30, 20, 69, 22))
        self.comboBox1.setObjectName("comboBox1")
        self.voltage_meter = QtWidgets.QLabel(self.centralwidget)
        self.voltage_meter.setGeometry(QtCore.QRect(780, 10, 131, 31))
        self.voltage_meter.setObjectName("voltage_meter")
        self.update_time = QtWidgets.QLabel(self.centralwidget)
        self.update_time.setGeometry(QtCore.QRect(890, 10, 221, 31))
        self.update_time.setObjectName("update_time")
        self.graphicsView_3 = pg.PlotWidget(self.centralwidget, axisItems = {'bottom': self.date_axis_2})
        self.graphicsView_3.setGeometry(QtCore.QRect(610, 280, 471, 221))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 380, 531, 321))
        self.groupBox_2.setObjectName("groupBox_2")
        self.graphicsViewII = pg.ImageView(self.groupBox_2)
        self.graphicsViewII.setGeometry(QtCore.QRect(10, 20, 511, 281))
        self.graphicsViewII.setObjectName("graphicsViewII")
        self.graphicsView_4 = pg.PlotWidget(self.centralwidget, axisItems = {'bottom': self.date_axis_3})
        self.graphicsView_4.setGeometry(QtCore.QRect(610, 510, 471, 221))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(620, 750, 121, 21))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1096, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.label2.setText(_translate("MainWindow", "TextLabel"))
        self.voltage_meter.setText(_translate("MainWindow", "TextLabel"))
        self.update_time.setText(_translate("MainWindow", "TextLabel"))
        self.groupBox_2.setTitle(_translate("MainWindow", "GroupBox"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
